export const REGISTER_USER = 'REGISTER_USER';
export const CONFIRM_REGISTRATION = 'CONFIRM_REGISTRATION';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';
